### ISSUE TITLE
error: 10: orphan end test

### ISSUE THREAD

**Issue by wavded** [tebeka/go2xunit#24]
```sh
› go version
go version go1.5.2 darwin/amd64
› go test -v | go2xunit -output tests.xml
error: 10: orphan end test
› go test -v
=== RUN   TestWelcome
=== RUN   TestGetMobileVersion
--- PASS: TestGetMobileVersion (0.00s)
=== RUN   TestDriverCoordinate
=== RUN   TestChat
=== RUN   TestNewCacher
=== RUN   TestCache_Fetch
--- PASS: TestCache_Fetch (0.10s)
--- PASS: TestNewCacher (0.00s)
--- PASS: TestWelcome (0.00s)
--- PASS: TestChat (0.00s)
--- PASS: TestDriverCoordinate (0.00s)
PASS
ok  	sampleproject	0.113s
```

Any ideas?  Running latest master of `go2xunit`

**Comment by wavded** [comment]
Some more insight.  If I run all my tests serially (no `t.Parallel()`), then it works fine.

**Comment by tebeka** [comment]
Yeah, parallel testing requires me to *guess* which I currently don't want to do :)
Other people have commented on this as well, I might consider a patch that tries to work with parallel testing only when a command line switch is given. Note that other people might be working on this (see [here](https://groups.google.com/forum/#!topic/golang-nuts/RAXk0ZmYKpg) for example)
