### ISSUE TITLE
Go 1.7 Subtests cause error "name mismatch"

### ISSUE THREAD

**Issue by aprice** [tebeka/go2xunit#27]
Go 1.7's new Subtests cause a slightly different output format, which go2xunit responds to with `error: 19: name mismatch (try disabling parallel mode)`. `go test` runs all the subtests under a test, then gives the results for the whole set:

```
=== RUN   TestPostResult
=== RUN   TestPostResult/ok
=== RUN   TestPostResult/withAlert
=== RUN   TestPostResult/blackout
=== RUN   TestPostResult/quiet
--- PASS: TestPostResult (0.41s)
    --- PASS: TestPostResult/ok (0.10s)
    --- PASS: TestPostResult/withAlert (0.10s)
    --- PASS: TestPostResult/blackout (0.10s)
    --- PASS: TestPostResult/quiet (0.10s)
```

**Comment by tebeka** [comment]
Thanks for reporting, will fix soon-ish.

As usual - patches are more than welcomed :)

**Comment by aprice** [comment]
I've been digging a bit and not entirely sure how to approach it, given I'm not that familiar with the implementation. It would seem you get enough detail from the `--- (PASS|FAIL|SKIP)` lines from the output to do the transform. What does matching it up to a `=== RUN` line do? Can that entire step just be removed?

**Comment by tebeka** [comment]
Sorry about the implementation - it's messy and I've been meaning to fix it for a while. I'll think about what you're saying and get back to you.

**Comment by aprice** [comment]
#28 is a possible fix, if you want to take a look.
