### ISSUE TITLE
Use table driven tests

### ISSUE THREAD

**Issue by tebeka** [tebeka/go2xunit#31]
Currently we have a lot of hand written tests for specific input. Convert that to a single utility function and sub tests.

**Comment by amibiz** [comment]
Can you give an example of such convertion?

**Comment by tebeka** [comment]
See [here](http://dave.cheney.net/2013/06/09/writing-table-driven-tests-in-go), probably change to use the new [subtests](https://golang.org/doc/go1.7#testing)
