### ISSUE TITLE
Update the Readme with new URL for downloading

### ISSUE THREAD

**Issue by subbu05** [tebeka/go2xunit#33]
Hi,

In the Readme its mentioned 
go get bitbucket.org/tebeka/go2xunit

But when we try this above command we get following
go get bitbucket.org/tebeka/go2xunit
package bitbucket.org/tebeka/go2xunit: https://api.bitbucket.org/1.0/repositories/tebeka/go2xunit: 404 NOT FOUND

Instead bitbucket.org I used github.com and was able to download it.

Please update to
**go get github.com/tebeka/go2xunit**

**Comment by tebeka** [comment]
Thanks! Done.
