### ISSUE TITLE
xUnit report XML data format

### ISSUE THREAD

**Issue by techtonik** [tebeka/go2xunit#35]
Is there a specification for xUnit XML format? I am trying to debug some issues with AppVeyor CI and couldn't find any.

**Comment by tebeka** [comment]
I'm not sure. I've modeled the output after Python's nose [xunit plugin](http://nose.readthedocs.io/en/latest/plugins/xunit.html) output.

Quick googling finds http://reflex.gforge.inria.fr/xunit.html#xunitReport (from [stackoverflow](http://stackoverflow.com/questions/10015689/what-is-the-reference-source-for-a-standard-xunit-report-xml))

**Comment by techtonik** [comment]
@tebeka I don't see that your tool produces report that http://reflex.gforge.inria.fr/xunit.html#xunitReport describes.

**Comment by tebeka** [comment]
Don't remember then :) I'm working with Jenkins which accepts the output.

**Comment by techtonik** [comment]
Maybe it is JUnit then? http://help.appveyor.com/discussions/problems/5264-xunit-results-are-not-being-parsed

**Comment by tebeka** [comment]
Probably. I really don't remember. Can you tell me what is the issue you have with AppVeyor CI?

**Comment by techtonik** [comment]
The issue with them is that their claim to support xUnit results format, but it actually xUnit.net format (which often drops its own .net extension), and the second issue is that when you upload report in invalid format, their service doesn't report any errors.

**Comment by tebeka** [comment]
Thanks for the clarification. You can generate nunit XML with `-xunitnet` flag.

**Comment by techtonik** [comment]
I don't use `go2xunit` (yet). There was a hope that it was build on some spec that is just missing from documentation.

**Comment by turbo** [comment]
Hi, support at AppVeyor confirmed that this tool outputs JUnit, not XUnit. Trying to push the results to xunit collection will fail.

**Comment by tebeka** [comment]
OK, looks like we don't support XUnit then. Patches are welcomed :)
