### ISSUE TITLE
time="N/A" not parsable as xs:decimal in our CI

### ISSUE THREAD

**Issue by markcampanelli-wf** [tebeka/go2xunit#54]
Setting GORACE="halt_on_error=1" with a race condition has caused problems with go2xunit properly formatting the raw `go test -race ...` output. There is no time in our output for the FAILed racing test (e.g., (5.32s) is missing) so that go2xunit puts time="N/A" into the XML, which causes our test reporter to choke, because it cannot convert N/A into a float. (Maybe NAN would be better here?)

**Comment by tebeka** [comment]
Thanks! I'll have a look this weekend. 
Can you check if changing the value to NaN fixes the issue@

**Comment by markcampanelli-wf** [comment]
Thanks @tebeka. Unfortunately, I put something like this into our CI processor:
```xml
<testcase classname="blah" name="TestBlah" time="NaN">...
```
and got this error:
```bash
...Element 'testcase', attribute 'time': 'NaN' is not a valid value of the atomic type 'xs:decimal'.
```
Of course, our parser may not be expecting the correct type here, but if 'xs:decimal' is the correct spec, then I don't think NaN would be supported.

**Comment by markcampanelli-wf** [comment]
Leaving the time string empty appears not to work either.

**Comment by tebeka** [comment]
Seems like [xs:decimal](http://books.xmlschemata.org/relaxng/ch19-77057.html) allows just numbers.

Maybe a value if `-1` then?

**Comment by markcampanelli-wf** [comment]
So it looks like my org patches the junit-7.xsd spec from a string to a decimal:
```xml
...
XML Schema Definition for JUnit, version 7.
SOURCE: Jenkins CI
https://svn.jenkins-ci.org/trunk/hudson/dtkit/dtkit-format/dtkit-junit-model/src/main/resources/com/thalesgroup/dtkit/junit/model/xsd/junit-7.xsd
...
            <!-- PATCH: Ensure only decimal values are used here -->
            <!-- <xs:attribute name="time" type="xs:string" use="optional"/> -->
            <xs:attribute name="time" type="xs:decimal" use="optional"/>
            <!-- END PATCH -->
```
However, this attribute is OPTIONAL in either case, and I just verified that leaving out the time indeed does NOT break our parser. So, perhaps you can just omit the time when it is N/A?

**Comment by markcampanelli-wf** [comment]
@tebeka Sorry that I didn't discover out "patch" to xs:decimal from xs:string until later. Would you say now that go2xunit is actually abiding by the intended spec?

**Comment by tebeka** [comment]
I'll look into it. A bit swamped right now (patches always welcomed ... ;)

**Comment by tebeka** [comment]
Change `N/A` to `0` for now
