### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by KantarBruceAdams** [tebeka/go2xunit#62]
It is unclear how to fix a project to use a particular version of a tool like go2xunit, see:

https://stackoverflow.com/questions/53086136/fixing-versions-of-tools-used-by-go
https://github.com/golang/go/issues/28512

Fixing that problem is out of scope for this project.
However:

If you have a solution to this it would be helpful to add it to the documentation.
If you don't have a solution to it would be helpful to document the potential issue.

**Comment by KantarBruceAdams** [comment]
It seems the current accepted way of achieving this is to use [retool](https://github.com/twitchtv/retool)

**Comment by tebeka** [comment]
Current with the new [go mod](https://github.com/golang/go/wiki/Modules) in go1.11 you can
`go get github.com/tebeka/go2xunit@v0.3.1`

**Comment by KantarBruceAdams** [comment]
It looks like the canonical solution is to create a fake tools package rather than getting a specific version. See https://stackoverflow.com/questions/53086136/fixing-versions-of-tools-used-by-go/53089261#53089261
